/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aceprogramming.mac;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        var world = new World(10, 10);
        System.out.println(world);

    }
}
